import Head from "next/head";
import React, { Fragment, useState } from "react";
import Footer from "./Footer";
import Header from "./Header";
import Sidebar from "./Sidebar";
import { useAuthContext } from "@/context/AuthContext";
import { useRouter } from "next/navigation";

const Layout = ({ children, title = "Sample Title" }) => {
  //console.log("layout", title)
  const [mobileNavsidebar, setMobileNavsidebar] = useState(false);

  const { user } = useAuthContext()
  const router = useRouter()

  React.useEffect(() => {
    if (user == null) router.push("/signup")
  }, [user])


  return (
    <Fragment>

      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex bg-gray-100 min-h-screen relative">

        <Sidebar mobileNavsidebar={mobileNavsidebar} />

        <div className="flex-grow text-gray-800">
          <Header mobileNavsidebar={mobileNavsidebar} setMobileNavsidebar={setMobileNavsidebar} />
          {children}
        </div>

        <Footer />
      </div>


    </Fragment>
  );
};

export default Layout;
